apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: something.apps.potato.com
spec:
  group: apps.potato.com
  names:
    kind: Some
    listKind: Somes
    plural: somes
    singular: some
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
